version: '3.8'

services:
  app:
    container_name: 'gpd-donation'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
    env_file:
      - ./.env
    ports:
      - "7071:7071"
