microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-gps-donation-service
    tag: "1.1.2-3-PAGOPA-1668-update-donation-helm"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /donations/info
      port: 7071
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /donations/info
      port: 7071
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 7071
  ingress:
    create: true
    host: "weudev.gps.internal.dev.platform.pagopa.it"
    path: /pagopa-gps-donation-service/(.*)
    servicePort: 7071
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 60 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: "pagopagpsdonationservice" # required to show cloud role name in application insights 
    FUNCTIONS_WORKER_RUNTIME: "node"
    ADD_DUE_DATE_DAYS: "15"
    ADD_RETENTION_DATE_DAYS: "15"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
  keyvault:
    name: "pagopa-d-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        tag: 1.1.0-4-PAGOPA-1212-migrazione-gha-pagopa-gps-donation-service
        repository: ghcr.io/pagopa/pagopa-gps-donation-service
