microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""

  image:
    repository: pagopadcommonacr.azurecr.io/pagopagpsdonationservice
    tag: "latest" #improve
    pullPolicy: Always

  livenessProbe:
    httpGet:
      path: /api/Info
      port: 7071
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /api/Info
      port: 7071
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 7071

  ingress:
    create: true
    host: "weudev.gps.internal.dev.platform.pagopa.it"
    path: /pagopa-gps-donation-service/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "40m"
    limits:
      memory: "300Mi"
      cpu: "150m"

  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: bbe47ad4-08b3-4925-94c5-1278e5819b86
          resourceGroupName: pagopa-d-gps-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-d-gps-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"

  envConfig:
    FUNCTIONS_WORKER_RUNTIME: "node"
    ADD_DUE_DATE_DAYS: "15"
    ADD_RETENTION_DATE_DAYS: "15"

  keyvault:
    name: "pagopa-d-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  nodeSelector: {}

  tolerations: []

  affinity: {}

